// Whereious master dataset
// 9 categories, 30 questions each (270 total)
// Format: { question, answer, lat, lng, info, category, regionRadiusKm }

export const WHEREIOUS_LANDMARKS = [
  { question: "Where is the Eiffel Tower?", answer: "Paris metro area, France", lat: 48.8584, lng: 2.2945, regionRadiusKm: 40, info: "Gustave Eiffel's 330m iron tower was built for the 1889 World's Fair and became the symbol of Paris.", category: "landmarks" },
  { question: "Where is the Colosseum?", answer: "Rome, Italy", lat: 41.8902, lng: 12.4922, regionRadiusKm: 35, info: "The Flavian Amphitheatre could hold around 50,000 spectators for gladiator games and public spectacles.", category: "landmarks" },
  { question: "Where is the Statue of Liberty?", answer: "New York City harbor, USA", lat: 40.6892, lng: -74.0445, regionRadiusKm: 40, info: "The copper statue on Liberty Island was a gift from France and greeted millions of immigrants arriving by sea.", category: "landmarks" },
  { question: "Where is Machu Picchu?", answer: "Sacred Valley near Cusco, Peru", lat: -13.1631, lng: -72.5450, regionRadiusKm: 40, info: "The 'lost city of the Incas' sits on a ridge above the Urubamba River high in the Peruvian Andes.", category: "landmarks" },
  { question: "Where is the Taj Mahal?", answer: "Agra district, India", lat: 27.1751, lng: 78.0421, regionRadiusKm: 30, info: "Shah Jahan's white marble mausoleum was built for his wife Mumtaz Mahal in the 1600s.", category: "landmarks" },
  { question: "Where is the Sydney Opera House?", answer: "Sydney Harbour, Australia", lat: -33.8568, lng: 151.2153, regionRadiusKm: 35, info: "Jørn Utzon's sail‑shaped performing arts centre defines the skyline of Sydney.", category: "landmarks" },
  { question: "Where is Christ the Redeemer?", answer: "Rio de Janeiro, Brazil", lat: -22.9519, lng: -43.2105, regionRadiusKm: 40, info: "The 30m‑tall Jesus statue stands on Corcovado mountain overlooking Rio and its beaches.", category: "landmarks" },
  { question: "Where is the Great Wall most famously visited?", answer: "Beijing region, China", lat: 40.3598, lng: 116.0206, regionRadiusKm: 120, info: "Popular sections like Badaling and Mutianyu lie in the hills north of Beijing.", category: "landmarks" },
  { question: "Where is Angkor Wat?", answer: "Siem Reap area, Cambodia", lat: 13.4125, lng: 103.8670, regionRadiusKm: 40, info: "The world's largest religious monument was the heart of the Khmer Empire.", category: "landmarks" },
  { question: "Where are the Pyramids of Giza?", answer: "Giza plateau near Cairo, Egypt", lat: 29.9792, lng: 31.1342, regionRadiusKm: 35, info: "Khufu's Great Pyramid and its neighbours rise on the desert edge west of Cairo.", category: "landmarks" },
  { question: "Where is Stonehenge?", answer: "Salisbury Plain, England", lat: 51.1789, lng: -1.8262, regionRadiusKm: 35, info: "The ring of standing stones was erected in stages between 3000 and 2000 BC.", category: "landmarks" },
  { question: "Where is Petra?", answer: "Wadi Musa area, Jordan", lat: 30.3285, lng: 35.4444, regionRadiusKm: 40, info: "The rock‑cut Nabataean city hides in a sandstone canyon accessed through the Siq.", category: "landmarks" },
  { question: "Where is the Acropolis?", answer: "Athens city, Greece", lat: 37.9715, lng: 23.7267, regionRadiusKm: 30, info: "The fortified hilltop holds the Parthenon and other classical temples above Athens.", category: "landmarks" },
  { question: "Where is Chichén Itzá?", answer: "Yucatán interior, Mexico", lat: 20.6843, lng: -88.5678, regionRadiusKm: 60, info: "The Maya‑Toltec city is famous for El Castillo, the stepped pyramid of Kukulkán.", category: "landmarks" },
  { question: "Where is the Golden Gate Bridge?", answer: "San Francisco Bay area, USA", lat: 37.8199, lng: -122.4783, regionRadiusKm: 40, info: "The red‑orange suspension bridge spans the strait between San Francisco and Marin County.", category: "landmarks" },
  { question: "Where is the Sagrada Família?", answer: "Barcelona, Spain", lat: 41.4036, lng: 2.1744, regionRadiusKm: 30, info: "Antoni Gaudí's still‑unfinished basilica dominates the Eixample district of Barcelona.", category: "landmarks" },
  { question: "Where is Neuschwanstein Castle?", answer: "Bavarian Alps near Füssen, Germany", lat: 47.5576, lng: 10.7498, regionRadiusKm: 40, info: "King Ludwig II's fairy‑tale castle looks over lakes and mountains near the Austrian border.", category: "landmarks" },
  { question: "Where is the Alhambra?", answer: "Granada, Spain", lat: 37.1760, lng: -3.5881, regionRadiusKm: 35, info: "The hilltop Nasrid palace complex overlooks the city of Granada and the Sierra Nevada.", category: "landmarks" },
  { question: "Where is Mount Rushmore?", answer: "Black Hills, South Dakota, USA", lat: 43.8791, lng: -103.4591, regionRadiusKm: 60, info: "The granite cliff face bears 18m‑high carvings of four US presidents.", category: "landmarks" },
  { question: "Where is the Forbidden City?", answer: "Central Beijing, China", lat: 39.9163, lng: 116.3972, regionRadiusKm: 30, info: "The walled palace complex once housed Chinese emperors and their courts.", category: "landmarks" },
  { question: "Where is the Blue Mosque?", answer: "Historic peninsula of Istanbul, Turkey", lat: 41.0054, lng: 28.9768, regionRadiusKm: 30, info: "Sultan Ahmed Mosque stands opposite Hagia Sophia in Istanbul's old city.", category: "landmarks" },
  { question: "Where is the CN Tower?", answer: "Downtown Toronto, Canada", lat: 43.6426, lng: -79.3871, regionRadiusKm: 30, info: "The 553m tower dominates Toronto's skyline beside Lake Ontario.", category: "landmarks" },
  { question: "Where is the Louvre Museum?", answer: "Central Paris, France", lat: 48.8606, lng: 2.3376, regionRadiusKm: 25, info: "The former royal palace now houses one of the world's largest art collections.", category: "landmarks" },
  { question: "Where is the Tower of London?", answer: "Thames bend in London, England", lat: 51.5081, lng: -0.0759, regionRadiusKm: 25, info: "The Norman fortress guarded the City of London and held royal prisoners for centuries.", category: "landmarks" },
  { question: "Where is the Brandenburg Gate?", answer: "Central Berlin, Germany", lat: 52.5163, lng: 13.3777, regionRadiusKm: 25, info: "The neoclassical gate once stood in no‑man's‑land beside the Berlin Wall.", category: "landmarks" },
  { question: "Where is the Leaning Tower of Pisa?", answer: "Pisa, Italy", lat: 43.7229, lng: 10.3966, regionRadiusKm: 25, info: "The freestanding campanile began tilting soon after construction started in the 1100s.", category: "landmarks" },
  { question: "Where is Uluru (Ayers Rock)?", answer: "Uluru–Kata Tjuta National Park, Australia", lat: -25.3444, lng: 131.0369, regionRadiusKm: 80, info: "The huge sandstone monolith rises from the desert in central Australia and is sacred to the Anangu people.", category: "landmarks" },
  { question: "Where is the Mecca Grand Mosque?", answer: "Mecca basin, Saudi Arabia", lat: 21.4225, lng: 39.8262, regionRadiusKm: 35, info: "Masjid al‑Haram surrounds the Kaaba, the holiest site in Islam.", category: "landmarks" },
  { question: "Where is the Christchurch Cathedral and quake‑damaged centre?", answer: "Christchurch city centre, New Zealand", lat: -43.5316, lng: 172.6362, regionRadiusKm: 25, info: "The 2011 earthquake badly damaged the Gothic cathedral and reshaped Christchurch's downtown.", category: "landmarks" }
];

export const WHEREIOUS_NATURE_REGIONS = [
  {
    question: "Where is the Amazon Rainforest mainly located?",
    answer: "Northern Brazil and Amazon Basin",
    lat: -3.0,
    lng: -60.0,
    regionRadiusKm: 600,
    // Very rough polygon for the core Amazon Basin (not exact political borders)
    regionPolygon: [
      [-5.0, -78.0],  // near Andes in Ecuador/Peru
      [2.0, -75.0],
      [5.0, -70.0],
      [5.0, -60.0],
      [3.0, -52.0],
      [-2.0, -49.0],
      [-8.0, -49.0],
      [-12.0, -55.0],
      [-12.0, -65.0],
      [-8.0, -72.0],
      [-5.0, -78.0]
    ],
    info: "The Amazon spans nine countries, but most of it lies in northern Brazil.",
    category: "nature"
  },
  {
    question: "Where is the Sahara Desert?",
    answer: "Central North Africa",
    lat: 23.5,
    lng: 13.0,
    regionRadiusKm: 900,
    // Very rough bounding polygon for central Sahara
    regionPolygon: [
      [30.0, -10.0],  // Morocco/Algeria region
      [33.0, 5.0],
      [31.0, 20.0],
      [25.0, 34.0],
      [18.0, 34.0],
      [15.0, 25.0],
      [15.0, 10.0],
      [18.0, -5.0],
      [24.0, -10.0],
      [30.0, -10.0]
    ],
    info: "The world's largest hot desert stretches across 11 countries from the Atlantic to the Red Sea.",
    category: "nature"
  },
  { question: "Where is the Great Barrier Reef?", answer: "Northeast coast of Australia", lat: -18.0, lng: 147.0, regionRadiusKm: 700, info: "The reef runs for 2,300km along Queensland's tropical coast in the Coral Sea.", category: "nature" },
  { question: "Where is the Serengeti?", answer: "Northern Tanzania plains", lat: -2.3333, lng: 34.8333, regionRadiusKm: 250, info: "The Serengeti ecosystem hosts the great wildebeest migration between Tanzania and Kenya.", category: "nature" },
  { question: "Where are the Galápagos Islands?", answer: "Pacific Ocean off Ecuador", lat: -0.9538, lng: -90.9656, regionRadiusKm: 200, info: "The volcanic archipelago lies about 900km west of mainland Ecuador.", category: "nature" },
  { question: "Where are the Himalayas' highest peaks?", answer: "Border of Nepal and Tibet", lat: 27.99, lng: 86.92, regionRadiusKm: 250, info: "Everest and neighbouring giants stand along the crest between Nepal and the Tibetan Plateau.", category: "nature" },
  { question: "Where is the Antarctic Peninsula?", answer: "Northern tip of Antarctica", lat: -64.0, lng: -61.0, regionRadiusKm: 400, info: "The finger of land pointing toward South America is the most accessible part of the continent.", category: "nature" },
  { question: "Where is the Okavango Delta?", answer: "Northern Botswana", lat: -19.3, lng: 22.8, regionRadiusKm: 200, info: "The Okavango River spreads into an inland delta in the Kalahari, creating a seasonal oasis for wildlife.", category: "nature" },
  { question: "Where is the Grand Canyon?", answer: "Northern Arizona, USA", lat: 36.0544, lng: -112.1401, regionRadiusKm: 120, info: "The Colorado River carved this immense gorge on the Colorado Plateau.", category: "nature" },
  { question: "Where is Patagonia's icefield and peaks?", answer: "Southern Andes in Chile and Argentina", lat: -49.3, lng: -73.3, regionRadiusKm: 400, info: "The Southern Patagonian Ice Field feeds dramatic glaciers and jagged peaks like Fitz Roy and Torres del Paine.", category: "nature" },
  { question: "Where is the Sundarbans mangrove forest?", answer: "Ganges‑Brahmaputra delta, Bangladesh/India", lat: 21.95, lng: 89.18, regionRadiusKm: 170, info: "The Sundarbans straddle the border between India and Bangladesh along the Bay of Bengal.", category: "nature" },
  { question: "Where is the Atacama Desert?", answer: "Northern Chile plateau", lat: -24.5, lng: -69.25, regionRadiusKm: 250, info: "The hyper‑arid Atacama lies between the Andes and the Pacific coastal range.", category: "nature" },
  { question: "Where is Yellowstone's geyser region?", answer: "Northwest Wyoming, USA", lat: 44.4605, lng: -110.8281, regionRadiusKm: 120, info: "Old Faithful and other geysers sit above a giant volcanic caldera mostly in Wyoming.", category: "nature" },
  { question: "Where is the Norwegian fjords region?", answer: "Western coast of Norway", lat: 61.0, lng: 6.5, regionRadiusKm: 300, info: "Deep glacial fjords cut into the coastline between Stavanger and Trondheim.", category: "nature" },
  { question: "Where are the Canadian Rockies around Banff?", answer: "Alberta–British Columbia border, Canada", lat: 51.4, lng: -116.2, regionRadiusKm: 200, info: "Banff and Jasper national parks protect the most famous section of the Rockies in Canada.", category: "nature" },
  { question: "Where is the Gobi Desert?", answer: "Mongolia and northern China", lat: 42.5, lng: 105.0, regionRadiusKm: 600, info: "The cold desert stretches across the rain shadow of the Himalayas in East Asia.", category: "nature" },
  { question: "Where is the Great Lakes region?", answer: "Canada–USA border around the Great Lakes", lat: 45.0, lng: -84.0, regionRadiusKm: 450, info: "Lakes Superior, Michigan, Huron, Erie and Ontario form the world's largest freshwater lake system.", category: "nature" },
  { question: "Where is the Black Forest?", answer: "Southwest Germany", lat: 48.1, lng: 8.2, regionRadiusKm: 120, info: "The Schwarzwald covers the hills between the Rhine valley and the upper Danube.", category: "nature" },
  { question: "Where is Kruger National Park?", answer: "Northeast South Africa", lat: -23.9884, lng: 31.5547, regionRadiusKm: 180, info: "Kruger stretches for 360km along South Africa's borders with Mozambique and Zimbabwe.", category: "nature" },
  { question: "Where is the Dolomites mountain region?", answer: "Northeast Italian Alps", lat: 46.41, lng: 11.84, regionRadiusKm: 120, info: "The pale limestone peaks lie between the Alps and the Venetian plain.", category: "nature" },
  { question: "Where is the Great Blue Hole and Belize Barrier Reef?", answer: "Offshore Belize, Caribbean Sea", lat: 17.3152, lng: -87.5347, regionRadiusKm: 120, info: "The famous marine sinkhole sits inside the Lighthouse Reef atoll off Belize's coast.", category: "nature" },
  {
    question: "Where is the Iceland Golden Circle region?",
    answer: "Southwest Iceland",
    lat: 64.255,
    lng: -20.9,
    regionRadiusKm: 120,
    // Approximate polygon around the Golden Circle / southwest Iceland tourist region
    regionPolygon: [
      [64.6, -23.0],
      [64.6, -20.0],
      [64.1, -18.5],
      [63.6, -18.5],
      [63.6, -22.5],
      [64.0, -23.5],
      [64.6, -23.0]
    ],
    info: "Thingvellir, Geysir and Gullfoss form the classic sightseeing loop near Reykjavík.",
    category: "nature"
  },
  { question: "Where is the Carpathian Mountains wilderness?", answer: "Arc from Slovakia to Romania", lat: 47.0, lng: 24.5, regionRadiusKm: 350, info: "The horse‑shoe shaped range contains some of Europe's largest remaining forests and brown bear populations.", category: "nature" },
  { question: "Where is the Great Plains grassland?", answer: "Central North America", lat: 39.0, lng: -100.0, regionRadiusKm: 700, info: "The Great Plains stretch from Texas to Canada between the Rockies and the Mississippi.", category: "nature" },
  { question: "Where is the Red Sea coral region?", answer: "Between northeast Africa and Arabia", lat: 22.0, lng: 38.0, regionRadiusKm: 500, info: "The Red Sea's warm, salty waters support rich coral reefs along Egypt, Sudan and Saudi Arabia.", category: "nature" },
  { question: "Where is the East African Rift lakes region?", answer: "Rift Valley in Kenya and Tanzania", lat: -2.0, lng: 34.0, regionRadiusKm: 350, info: "A chain of deep lakes including Turkana, Naivasha and Tanganyika follows the rift.", category: "nature" },
  { question: "Where is the Fiordland and Milford Sound region?", answer: "Southwest South Island, New Zealand", lat: -44.6, lng: 167.9, regionRadiusKm: 160, info: "Glacially carved fiords slice into the coast of New Zealand's Fiordland National Park.", category: "nature" },
  { question: "Where is the Pantanal wetland?", answer: "Brazil/Bolivia/Paraguay border region", lat: -17.8, lng: -57.6, regionRadiusKm: 350, info: "Seasonal flooding turns this vast basin into the world's largest tropical wetland.", category: "nature" },
  { question: "Where is the eye‑like Richat Structure (Eye of the Sahara)?", answer: "Central Mauritania", lat: 21.124, lng: -11.396, regionRadiusKm: 120, info: "The 40km‑wide circular feature stands out in satellite images of the Sahara.", category: "nature" }
];

export const WHEREIOUS_HISTORY_REGIONS = [
  { question: "Where did the D-Day landings take place?", answer: "Normandy coast, France", lat: 49.3736, lng: -0.8632, regionRadiusKm: 120, info: "Allied forces stormed several beaches along a stretch of the Normandy coastline on 6 June 1944.", category: "history" },
  { question: "Where did the Renaissance first flourish?", answer: "Florence and Tuscany, Italy", lat: 43.7696, lng: 11.2558, regionRadiusKm: 80, info: "Patrons in Florence funded artists and thinkers whose work sparked the European Renaissance.", category: "history" },
  { question: "Where did the Roman Empire originate?", answer: "Latium around Rome, Italy", lat: 41.8933, lng: 12.4829, regionRadiusKm: 120, info: "Rome grew from a small city on the Tiber into the centre of an empire around the Mediterranean.", category: "history" },
  { question: "Where did the American Revolution break out first?", answer: "Boston and surrounding Massachusetts, USA", lat: 42.3601, lng: -71.0589, regionRadiusKm: 120, info: "Clashes at Lexington and Concord near Boston in 1775 marked the start of the war.", category: "history" },
  { question: "Where did the French Revolution erupt?", answer: "Paris basin, France", lat: 48.8534, lng: 2.3488, regionRadiusKm: 80, info: "The storming of the Bastille and the upheavals that followed were centered on Paris.", category: "history" },
  { question: "Where did the Berlin Wall divide a city?", answer: "Berlin, Germany", lat: 52.5163, lng: 13.3777, regionRadiusKm: 30, info: "The Wall looped around West Berlin from 1961 to 1989, separating it from East Germany.", category: "history" },
  { question: "Where did the Cuban Missile Crisis focus on?", answer: "Havana and western Cuba", lat: 23.1136, lng: -82.3666, regionRadiusKm: 200, info: "Soviet missiles were secretly installed on the island within range of the US mainland.", category: "history" },
  { question: "Where did the 1917 Russian Revolution begin?", answer: "Petrograd (St. Petersburg), Russia", lat: 59.9343, lng: 30.3351, regionRadiusKm: 80, info: "Strikes and mutinies in Petrograd toppled the Tsar and set up a provisional government.", category: "history" },
  { question: "Where was the Ottoman Empire centred for centuries?", answer: "Istanbul and western Anatolia, Turkey", lat: 41.0082, lng: 28.9784, regionRadiusKm: 200, info: "From Constantinople the Ottomans ruled lands around the eastern Mediterranean.", category: "history" },
  { question: "Where were the classical Greek city-states concentrated?", answer: "Attica and the Peloponnese, Greece", lat: 37.7, lng: 23.6, regionRadiusKm: 220, info: "Athens, Sparta and other poleis clustered around the Aegean coasts and islands.", category: "history" },
  { question: "Where did the Industrial Revolution first take off?", answer: "Midlands and northern England, UK", lat: 53.5, lng: -1.5, regionRadiusKm: 200, info: "Coalfields and textile towns around Manchester, Birmingham and Leeds drove early industrialisation.", category: "history" },
  { question: "Where did the Silk Road funnel into Europe?", answer: "Eastern Mediterranean and Anatolia region", lat: 38.0, lng: 35.0, regionRadiusKm: 400, info: "Caravans from Central Asia often passed through Anatolian and Levantine ports.", category: "history" },
  { question: "Where was the Aztec Empire centred?", answer: "Valley of Mexico", lat: 19.4326, lng: -99.1332, regionRadiusKm: 100, info: "Tenochtitlan stood on an island in the lake‑filled basin now occupied by Mexico City.", category: "history" },
  { question: "Where was the Inca Empire centred?", answer: "Cusco region in the Andes, Peru", lat: -13.5320, lng: -71.9675, regionRadiusKm: 180, info: "Cusco served as the capital of an empire stretching along the spine of South America.", category: "history" },
  { question: "Where did the Rwandan genocide begin?", answer: "Kigali region, Rwanda", lat: -1.9441, lng: 30.0619, regionRadiusKm: 70, info: "Killings started in Kigali in April 1994 and spread rapidly across the country.", category: "history" },
  { question: "Where did most of the Vietnam War take place?", answer: "S‑shaped territory of Vietnam", lat: 16.0, lng: 107.5, regionRadiusKm: 550, info: "Combat stretched from the demilitarized zone in the centre to the Mekong Delta in the south.", category: "history" },
  { question: "Where did the American Civil War begin with Fort Sumter?", answer: "Charleston harbor, South Carolina, USA", lat: 32.7523, lng: -79.8747, regionRadiusKm: 80, info: "Confederate guns fired on the Union fort in April 1861 in Charleston Bay.", category: "history" },
  { question: "Where were the Crusader States clustered?", answer: "Levantine Mediterranean coast", lat: 33.5, lng: 35.0, regionRadiusKm: 350, info: "Crusader strongholds lined the coasts of modern Israel, Lebanon and Syria.", category: "history" },
  { question: "Where was ancient Mesopotamia located?", answer: "Tigris–Euphrates plain, Iraq", lat: 33.0, lng: 44.0, regionRadiusKm: 350, info: "Cities like Uruk and Babylon rose between the Tigris and Euphrates rivers.", category: "history" },
  { question: "Where was the core of ancient Egypt?", answer: "Nile Valley between Cairo and Luxor", lat: 27.5, lng: 31.0, regionRadiusKm: 400, info: "Fertile floodplains along the Nile supported pharaonic civilisation for millennia.", category: "history" },
  { question: "Where did the Mongol Empire radiate from?", answer: "Mongolian steppe", lat: 47.0, lng: 104.0, regionRadiusKm: 500, info: "Genghis Khan united nomadic tribes on the high steppe north of China.", category: "history" },
  { question: "Where was the Mayan civilisation centred?", answer: "Yucatán and Guatemala highlands", lat: 17.0, lng: -89.0, regionRadiusKm: 400, info: "Major Maya cities dotted the tropical lowlands and uplands of Mesoamerica.", category: "history" },
  { question: "Where did the Norman conquest culminate in 1066?", answer: "Hastings region, southern England", lat: 50.9112, lng: 0.4875, regionRadiusKm: 60, info: "William defeated Harold near Hastings, reshaping English history.", category: "history" },
  { question: "Where was Titanic's last departure region in Europe?", answer: "Cobh and the Irish south coast", lat: 51.8503, lng: -8.2964, regionRadiusKm: 80, info: "The liner left Queenstown (now Cobh) before heading into the North Atlantic.", category: "history" },
  { question: "Where did the Spanish Armada battle the English navy?", answer: "English Channel", lat: 50.0, lng: -2.0, regionRadiusKm: 300, info: "Fighting and storms scattered the Armada in the Channel and around Scotland and Ireland.", category: "history" },
  { question: "Where was the Persian Empire's heartland?", answer: "Iranian plateau centred on Persepolis", lat: 29.934, lng: 52.891, regionRadiusKm: 350, info: "The Achaemenid Persians ruled from cities in modern‑day Iran.", category: "history" },
  { question: "Where was the Byzantine Empire centred?", answer: "Constantinople and western Anatolia", lat: 41.0082, lng: 28.9784, regionRadiusKm: 250, info: "The eastern Roman Empire survived for a thousand years after Rome fell.", category: "history" },
  { question: "Where did the US civil rights marches make headlines?", answer: "Deep South of the United States", lat: 32.4, lng: -86.3, regionRadiusKm: 450, info: "Cities like Montgomery, Birmingham and Selma in Alabama became flashpoints.", category: "history" },
  { question: "Where did the Arab Spring first spark?", answer: "Central Tunisia", lat: 35.0382, lng: 9.4839, regionRadiusKm: 180, info: "Protests starting in Sidi Bouzid spread across Tunisia and then the region.", category: "history" },
  { question: "Where did the UN founding conference take place?", answer: "San Francisco Bay Area, USA", lat: 37.7784, lng: -122.4202, regionRadiusKm: 60, info: "Delegates from 50 nations met in San Francisco in 1945 to draft the UN Charter.", category: "history" }
];

export const WHEREIOUS_GEOGRAPHY = [
  { question: "Where is the Iberian Peninsula?", answer: "Spain and Portugal in southwest Europe", lat: 40.0, lng: -3.0, regionRadiusKm: 450, info: "The peninsula is bounded by the Atlantic Ocean and the Mediterranean Sea.", category: "geography" },
  { question: "Where is the Balkan Peninsula?", answer: "Southeast Europe around the Adriatic and Aegean", lat: 42.0, lng: 21.0, regionRadiusKm: 500, info: "The Balkans include countries such as Greece, Albania, Bulgaria and much of former Yugoslavia.", category: "geography" },
  { question: "Where is the Scandinavian Peninsula?", answer: "Norway and Sweden in northern Europe", lat: 64.0, lng: 15.0, regionRadiusKm: 700, info: "The long peninsula stretches between the North Sea and the Baltic.", category: "geography" },
  { question: "Where is the Horn of Africa?", answer: "Easternmost projection of Africa", lat: 8.0, lng: 45.0, regionRadiusKm: 600, info: "The Horn includes Somalia, Ethiopia, Eritrea and Djibouti.", category: "geography" },
  { question: "Where is the Middle East on the map?", answer: "Region around the eastern Mediterranean and Persian Gulf", lat: 29.0, lng: 41.0, regionRadiusKm: 900, info: "The term usually covers countries from Egypt and Turkey to Iran and the Arabian Peninsula.", category: "geography" },
  { question: "Where is mainland Southeast Asia?", answer: "Indochina peninsula", lat: 15.0, lng: 104.0, regionRadiusKm: 600, info: "Myanmar, Thailand, Laos, Cambodia and Vietnam form the mainland part of Southeast Asia.", category: "geography" },
  { question: "Where is the Caribbean region?", answer: "Island arc between North and South America", lat: 17.0, lng: -66.0, regionRadiusKm: 700, info: "The Caribbean Sea is ringed by the Greater and Lesser Antilles and coasts of Central and South America.", category: "geography" },
  { question: "Where is the Mediterranean Sea basin?", answer: "Between Europe, Africa and Asia", lat: 37.0, lng: 15.0, regionRadiusKm: 900, info: "An almost enclosed sea connected to the Atlantic only through the Strait of Gibraltar.", category: "geography" },
  { question: "Where is the Persian Gulf?", answer: "Between Arabia and Iran", lat: 26.0, lng: 52.0, regionRadiusKm: 300, info: "The shallow gulf lies between the Arabian Peninsula and the Iranian Plateau.", category: "geography" },
  { question: "Where is the Himalaya mountain region?", answer: "Arc between India and the Tibetan Plateau", lat: 28.0, lng: 86.0, regionRadiusKm: 700, info: "The Himalayas stretch from Pakistan to Myanmar, separating the Indian subcontinent from Central Asia.", category: "geography" },
  { question: "Where is the Andes mountain chain?", answer: "Western edge of South America", lat: -15.0, lng: -72.0, regionRadiusKm: 900, info: "The Andes run for 7,000km through seven countries from Venezuela to Chile.", category: "geography" },
  { question: "Where are the Great Plains?", answer: "Central North America", lat: 39.0, lng: -100.0, regionRadiusKm: 700, info: "The grasslands stretch from Texas to Alberta east of the Rocky Mountains.", category: "geography" },
  { question: "Where is the Sahel region?", answer: "Semi‑arid belt south of the Sahara", lat: 14.0, lng: 1.0, regionRadiusKm: 800, info: "The Sahel runs from Senegal in the west to Sudan in the east.", category: "geography" },
  { question: "Where is the Baltic Sea region?", answer: "Northern Europe around the Baltic Sea", lat: 58.0, lng: 20.0, regionRadiusKm: 600, info: "Countries including Sweden, Finland, Estonia, Latvia and Lithuania border the Baltic.", category: "geography" },
  { question: "Where is the Benelux area?", answer: "Belgium, Netherlands and Luxembourg", lat: 51.0, lng: 5.0, regionRadiusKm: 250, info: "The three low‑lying countries sit on the North Sea coast of western Europe.", category: "geography" },
  { question: "Where is the Pacific Ring of Fire most active?", answer: "Rim of the Pacific Ocean", lat: 0.0, lng: -120.0, regionRadiusKm: 800, info: "A horseshoe‑shaped belt of volcanoes and earthquake zones arcs around the Pacific.", category: "geography" },
  { question: "Where is the Caucasus region?", answer: "Mountains between the Black Sea and Caspian Sea", lat: 42.3, lng: 44.6, regionRadiusKm: 300, info: "The Caucasus separates Eastern Europe from Western Asia.", category: "geography" },
  { question: "Where is the Tibetan Plateau?", answer: "High plateau north of the Himalayas", lat: 32.0, lng: 88.0, regionRadiusKm: 600, info: "Often called the Roof of the World, it averages over 4,000m in elevation.", category: "geography" },
  { question: "Where is the Gulf of Mexico?", answer: "Basin between the US, Mexico and Cuba", lat: 25.0, lng: -90.0, regionRadiusKm: 500, info: "A warm semi‑enclosed sea of the western Atlantic Ocean.", category: "geography" },
  { question: "Where is the Aegean Sea?", answer: "Between Greece and Turkey", lat: 38.5, lng: 25.0, regionRadiusKm: 250, info: "The Aegean is dotted with Greek islands between the Greek mainland and Anatolia.", category: "geography" },
  { question: "Where is the English Channel?", answer: "Between southern England and northern France", lat: 50.0, lng: -2.0, regionRadiusKm: 250, info: "The Channel connects the Atlantic Ocean to the North Sea.", category: "geography" },
  { question: "Where is the Red Sea?", answer: "Between northeast Africa and the Arabian Peninsula", lat: 20.0, lng: 38.0, regionRadiusKm: 600, info: "The long narrow sea links the Suez Canal to the Gulf of Aden and Indian Ocean.", category: "geography" },
  { question: "Where is the Indian subcontinent?", answer: "Peninsula south of the Himalayas", lat: 22.0, lng: 78.0, regionRadiusKm: 900, info: "The subcontinent includes India, Pakistan, Bangladesh, Nepal and Sri Lanka.", category: "geography" },
  { question: "Where is the North Sea?", answer: "Sea between Britain and mainland Europe", lat: 56.0, lng: 3.0, regionRadiusKm: 400, info: "The North Sea lies between the UK, Norway, Denmark, Germany, the Netherlands and Belgium.", category: "geography" },
  { question: "Where is the Alpine region of Europe?", answer: "Mountain arc from France to Slovenia", lat: 46.5, lng: 10.0, regionRadiusKm: 450, info: "The Alps curve across eight countries in central Europe.", category: "geography" },
  { question: "Where is the Amazon Basin?", answer: "Interior of northern South America", lat: -4.0, lng: -62.0, regionRadiusKm: 900, info: "The drainage basin of the Amazon River covers an area larger than the EU.", category: "geography" },
  { question: "Where is the Danube River basin?", answer: "Central and eastern Europe", lat: 46.5, lng: 20.0, regionRadiusKm: 600, info: "The Danube flows from Germany to the Black Sea through 10 countries.", category: "geography" },
  { question: "Where is South Asia's monsoon belt mostly located?", answer: "India and surrounding region", lat: 20.0, lng: 78.0, regionRadiusKm: 800, info: "Moist monsoon winds bring seasonal rains to the subcontinent each summer.", category: "geography" },
  { question: "Where is most land inside the Arctic Circle?", answer: "Northern Scandinavia, Russia and Canada", lat: 68.0, lng: 35.0, regionRadiusKm: 1200, info: "Arctic lands ring the polar ocean from Norway across Russia to Alaska and Canada.", category: "geography" }
];

export const WHEREIOUS_PEOPLE = [
  { question: "Where was Albert Einstein born?", answer: "Ulm region, Germany", lat: 48.3984, lng: 9.9916, regionRadiusKm: 60, info: "Einstein was born in Ulm in 1879 before growing up in Munich and later moving to Switzerland.", category: "people" },
  { question: "Where was Nelson Mandela from?", answer: "Eastern Cape, South Africa", lat: -31.6, lng: 28.8, regionRadiusKm: 250, info: "Mandela was born in the village of Mvezo and grew up in the Transkei region.", category: "people" },
  { question: "Where was Mahatma Gandhi born?", answer: "Gujarat, India", lat: 21.64, lng: 69.61, regionRadiusKm: 200, info: "Gandhi was born in the coastal town of Porbandar in western India.", category: "people" },
  { question: "Where did Martin Luther King Jr. grow up and lead?", answer: "US Deep South around Atlanta, Georgia", lat: 33.7490, lng: -84.3880, regionRadiusKm: 250, info: "King was born in Atlanta and led campaigns across the American South.", category: "people" },
  { question: "Where was Cleopatra's Egypt centred?", answer: "Nile Delta and Alexandria region", lat: 31.2001, lng: 29.9187, regionRadiusKm: 180, info: "Cleopatra ruled from Alexandria on Egypt's Mediterranean coast.", category: "people" },
  { question: "Where was Julius Caesar's Rome?", answer: "Rome and central Italy", lat: 41.8933, lng: 12.4829, regionRadiusKm: 120, info: "Caesar rose to power in the late Roman Republic centred on Rome.", category: "people" },
  { question: "Where was Leonardo da Vinci from?", answer: "Tuscany, Italy", lat: 43.8187, lng: 10.9254, regionRadiusKm: 120, info: "Leonardo was born in the town of Vinci near Florence.", category: "people" },
  { question: "Where was Wolfgang Amadeus Mozart from?", answer: "Salzburg region, Austria", lat: 47.8024, lng: 13.0443, regionRadiusKm: 70, info: "Mozart was born and spent his early years in Salzburg before moving to Vienna.", category: "people" },
  { question: "Where was Ludwig van Beethoven from?", answer: "Bonn and the Rhineland, Germany", lat: 50.7374, lng: 7.0982, regionRadiusKm: 80, info: "Beethoven was born in Bonn and later lived in Vienna.", category: "people" },
  { question: "Where was William Shakespeare from?", answer: "Stratford‑upon‑Avon and London, England", lat: 52.1917, lng: -1.7073, regionRadiusKm: 160, info: "Shakespeare was born in Stratford and wrote for theatres in London.", category: "people" },
  { question: "Where was Joan of Arc from?", answer: "Northeastern France around Lorraine", lat: 48.66, lng: 6.16, regionRadiusKm: 200, info: "Joan was born in Domrémy in the duchy of Bar, now in Lorraine.", category: "people" },
  { question: "Where was Marie Curie from originally?", answer: "Warsaw region, Poland", lat: 52.2297, lng: 21.0122, regionRadiusKm: 80, info: "Curie was born Maria Skłodowska in Warsaw before moving to Paris for research.", category: "people" },
  { question: "Where was Pablo Picasso mainly based during his career?", answer: "Barcelona and Paris", lat: 41.3851, lng: 2.1734, regionRadiusKm: 350, info: "Picasso spent key periods in both Barcelona and Paris, shifting modern art.", category: "people" },
  { question: "Where was Frida Kahlo from?", answer: "Mexico City area, Mexico", lat: 19.355, lng: -99.1617, regionRadiusKm: 80, info: "Kahlo lived most of her life in the Casa Azul in Coyoacán, Mexico City.", category: "people" },
  { question: "Where was Confucius from?", answer: "Shandong region, eastern China", lat: 35.597, lng: 116.985, regionRadiusKm: 200, info: "Confucius was born in or near Qufu in today's Shandong Province.", category: "people" },
  { question: "Where was Genghis Khan from?", answer: "Mongolian steppe", lat: 47.5, lng: 102.0, regionRadiusKm: 400, info: "Temüjin was born into a nomadic family on the high steppe north of China.", category: "people" },
  { question: "Where was Socrates teaching and debating?", answer: "Athens, Greece", lat: 37.9715, lng: 23.7267, regionRadiusKm: 40, info: "Socrates spent his life discussing philosophy in the public spaces of Athens.", category: "people" },
  { question: "Where was Winston Churchill's political base?", answer: "London and southeast England, UK", lat: 51.5074, lng: -0.1278, regionRadiusKm: 80, info: "Churchill represented several constituencies but governed from London.", category: "people" },
  { question: "Where was Barack Obama politically based before becoming US president?", answer: "Chicago region, Illinois, USA", lat: 41.8781, lng: -87.6298, regionRadiusKm: 80, info: "Obama worked as a community organiser and politician in Chicago.", category: "people" },
  { question: "Where was Angela Merkel's long-time political base?", answer: "Berlin and Brandenburg region, Germany", lat: 52.52, lng: 13.405, regionRadiusKm: 140, info: "Merkel represented a constituency in northeastern Germany and governed from Berlin.", category: "people" },
  { question: "Where was Malala Yousafzai from?", answer: "Swat Valley, Pakistan", lat: 34.7717, lng: 72.3606, regionRadiusKm: 80, info: "Malala grew up in the town of Mingora in the Swat Valley of northwest Pakistan.", category: "people" },
  { question: "Where was Che Guevara from originally?", answer: "Argentina", lat: -31.42, lng: -64.19, regionRadiusKm: 400, info: "Ernesto 'Che' Guevara was born in Rosario and grew up in Córdoba Province.", category: "people" },
  { question: "Where was Fidel Castro's revolution based?", answer: "Sierra Maestra mountains in eastern Cuba", lat: 20.0, lng: -76.0, regionRadiusKm: 180, info: "Castro's guerrillas operated from remote mountain camps before taking Havana.", category: "people" },
  { question: "Where was Alexander the Great's original kingdom?", answer: "Macedonia in northern Greece", lat: 40.992, lng: 22.88, regionRadiusKm: 160, info: "Alexander inherited the kingdom of Macedon north of classical Greece.", category: "people" },
  { question: "Where was Tenzing Norgay from?", answer: "Sherpa communities of Nepal", lat: 27.72, lng: 86.71, regionRadiusKm: 80, info: "Tenzing was born in the Khumbu region near Everest.", category: "people" },
  { question: "Where was Yuri Gagarin from?", answer: "Western Russia", lat: 55.75, lng: 38.25, regionRadiusKm: 250, info: "Gagarin was born in a village west of Moscow before joining the Soviet Air Force.", category: "people" },
  { question: "Where was Malcolm X most active?", answer: "Northern US cities, especially New York", lat: 40.7128, lng: -74.0060, regionRadiusKm: 200, info: "Malcolm X preached in Harlem and other northern US cities.", category: "people" },
  { question: "Where was Ada Lovelace from?", answer: "London, England", lat: 51.5074, lng: -0.1278, regionRadiusKm: 60, info: "Lovelace lived and worked among London's scientific circles in the 1800s.", category: "people" },
  { question: "Where was Florence Nightingale's work most famous?", answer: "Crimea and later London, UK", lat: 44.6, lng: 33.5, regionRadiusKm: 250, info: "Her nursing during the Crimean War and reforms in London hospitals transformed medicine.", category: "people" },
  { question: "Where was Sun Tzu's world centred?", answer: "Eastern China, ancient state regions", lat: 32.5, lng: 119.0, regionRadiusKm: 300, info: "The strategist is thought to have lived in ancient Wu or Qi in what is now eastern China.", category: "people" }
];

export const WHEREIOUS_RECORDS = [
  { question: "Where is the region with the world's tallest building today?", answer: "Dubai city, United Arab Emirates", lat: 25.1972, lng: 55.2744, regionRadiusKm: 40, info: "The Burj Khalifa rises above downtown Dubai.", category: "records" },
  { question: "Where is the region of the world's highest mountain?", answer: "Everest area in the Himalayas", lat: 27.9881, lng: 86.9250, regionRadiusKm: 80, info: "Mount Everest stands on the border between Nepal and the Tibet Autonomous Region of China.", category: "records" },
  { question: "Where is the world's deepest ocean trench?", answer: "Mariana Trench in the western Pacific", lat: 11.35, lng: 142.2, regionRadiusKm: 200, info: "The Challenger Deep in the trench reaches about 11,000m below sea level.", category: "records" },
  { question: "Where is the world's largest rainforest?", answer: "Amazon Basin in South America", lat: -4.0, lng: -62.0, regionRadiusKm: 900, info: "The Amazon rainforest covers much of Brazil and parts of eight other countries.", category: "records" },
  { question: "Where is the world's largest hot desert?", answer: "Central Sahara Desert", lat: 23.5, lng: 13.0, regionRadiusKm: 900, info: "The Sahara covers about 9.2 million km² in North Africa.", category: "records" },
  { question: "Where is the region with the world's coldest permanently inhabited town?", answer: "Yakutia in eastern Russia", lat: 63.45, lng: 143.2, regionRadiusKm: 400, info: "Settlements like Oymyakon in the Sakha Republic have recorded temperatures below −60°C.", category: "records" },
  { question: "Where is the world's largest coral reef system?", answer: "Great Barrier Reef off Queensland, Australia", lat: -18.0, lng: 147.0, regionRadiusKm: 700, info: "The reef stretches along 2,300km of Australia's northeast coast.", category: "records" },
  { question: "Where is the world's longest river system mainly located?", answer: "Nile River valley in northeast Africa", lat: 21.0, lng: 31.0, regionRadiusKm: 900, info: "The Nile flows north from central Africa to the Mediterranean through Sudan and Egypt.", category: "records" },
  { question: "Where is the world's largest freshwater lake by volume?", answer: "Lake Baikal region, Russia", lat: 53.5587, lng: 108.1650, regionRadiusKm: 200, info: "Lake Baikal holds about 20% of Earth’s unfrozen surface fresh water.", category: "records" },
  { question: "Where is the world's saltiest large lake?", answer: "Dead Sea basin between Israel, Palestine and Jordan", lat: 31.5590, lng: 35.4732, regionRadiusKm: 80, info: "The Dead Sea's salinity is over 30%, making swimming more like floating.", category: "records" },
  { question: "Where is the world's largest island that is not a continent?", answer: "Greenland", lat: 72.0, lng: -40.0, regionRadiusKm: 900, info: "Greenland is the world's largest island, mostly covered by ice.", category: "records" },
  { question: "Where is the world's smallest country?", answer: "Vatican City in Rome, Italy", lat: 41.9029, lng: 12.4534, regionRadiusKm: 10, info: "The microstate is enclaved within the city of Rome.", category: "records" },
  { question: "Where is the region of the world's most populous country?", answer: "East and central China", lat: 34.0, lng: 105.0, regionRadiusKm: 900, info: "China has long been the most populous country, though India is close and may surpass it.", category: "records" },
  { question: "Where is the world's busiest container port region?", answer: "Shanghai and the Yangtze River delta, China", lat: 31.2304, lng: 121.4737, regionRadiusKm: 120, info: "The Port of Shanghai moves more containers than any other port.", category: "records" },
  { question: "Where is the world's busiest passenger airport region?", answer: "Atlanta area, USA", lat: 33.6407, lng: -84.4277, regionRadiusKm: 40, info: "Hartsfield–Jackson Atlanta International Airport frequently tops global passenger statistics.", category: "records" },
  { question: "Where is the world's tallest waterfall?", answer: "Angel Falls region in Venezuela", lat: 5.9701, lng: -62.5362, regionRadiusKm: 120, info: "Angel Falls plunges nearly 1,000m from a table mountain in Canaima National Park.", category: "records" },
  { question: "Where was the world's hottest reliably recorded air temperature?", answer: "Death Valley, California, USA", lat: 36.24, lng: -116.82, regionRadiusKm: 120, info: "Furnace Creek in Death Valley has recorded temperatures over 54°C.", category: "records" },
  { question: "Where was one of the world's coldest air temperatures recorded?", answer: "Interior of Antarctica", lat: -78.5, lng: 106.0, regionRadiusKm: 600, info: "Satellite data and stations on the East Antarctic Plateau have recorded temperatures below −80°C.", category: "records" },
  { question: "Where is the world's longest cave system?", answer: "Mammoth Cave region, Kentucky, USA", lat: 37.1874, lng: -86.1007, regionRadiusKm: 80, info: "Hundreds of kilometres of passages have been surveyed in Mammoth Cave.", category: "records" },
  { question: "Where is the world's longest rail tunnel?", answer: "Gotthard Base Tunnel under the Swiss Alps", lat: 46.7, lng: 8.6, regionRadiusKm: 80, info: "The 57km tunnel runs under the Alps in central Switzerland.", category: "records" },
  { question: "Where is the world's highest capital city?", answer: "La Paz region, Bolivia", lat: -16.5, lng: -68.15, regionRadiusKm: 60, info: "La Paz sits around 3,650m above sea level in the Andes.", category: "records" },
  { question: "Where is the world's lowest national capital above sea level?", answer: "Baku region, Azerbaijan", lat: 40.4093, lng: 49.8671, regionRadiusKm: 60, info: "Baku lies below sea level on the Caspian Sea.", category: "records" },
  { question: "Where are the tallest tree species naturally found?", answer: "Coastal redwood belt in northern California, USA", lat: 41.3, lng: -124.0, regionRadiusKm: 150, info: "Coast redwoods grow along a narrow strip of the Pacific coast.", category: "records" },
  { question: "Where is the world's largest mangrove forest?", answer: "Sundarbans region, Bangladesh/India", lat: 21.95, lng: 89.18, regionRadiusKm: 170, info: "The Sundarbans cover thousands of square kilometres in the Ganges delta.", category: "records" },
  { question: "Where is the world's longest international land border?", answer: "US–Canada border region", lat: 49.0, lng: -95.0, regionRadiusKm: 900, info: "The border stretches over 8,800km including Alaska's boundary with Canada.", category: "records" },
  { question: "Where is the heartland of the world's most spoken native language?", answer: "Mandarin‑speaking China", lat: 34.5, lng: 112.5, regionRadiusKm: 700, info: "Northern and central China hold most native speakers of Mandarin Chinese.", category: "records" },
  { question: "Where is one of the world's most visited cities for tourism?", answer: "Paris region, France", lat: 48.8566, lng: 2.3522, regionRadiusKm: 60, info: "Paris regularly tops global rankings for international arrivals.", category: "records" },
  { question: "Where is the world's largest waterfall system by flow?", answer: "Iguazu Falls region on the Brazil–Argentina border", lat: -25.6953, lng: -54.4367, regionRadiusKm: 80, info: "Hundreds of cascades spread across nearly 3km of the Iguazu River.", category: "records" }
];

export const WHEREIOUS_SCIENCE_REGIONS = [
  { question: "Where is CERN and the Large Hadron Collider region?", answer: "Geneva area on the Swiss–French border", lat: 46.2322, lng: 6.0554, regionRadiusKm: 80, info: "A 27km underground ring straddles the border near Geneva.", category: "science" },
  { question: "Where is NASA's Mission Control?", answer: "Houston region, Texas, USA", lat: 29.559, lng: -95.09, regionRadiusKm: 60, info: "Johnson Space Center near Houston directs US human spaceflight.", category: "science" },
  { question: "Where was penicillin discovered?", answer: "London hospital laboratory, England", lat: 51.5178, lng: -0.1762, regionRadiusKm: 40, info: "Alexander Fleming made the discovery at St. Mary's Hospital in Paddington.", category: "science" },
  { question: "Where was the structure of DNA described?", answer: "Cambridge, England", lat: 52.2053, lng: 0.1218, regionRadiusKm: 40, info: "Watson and Crick worked at the Cavendish Laboratory in Cambridge.", category: "science" },
  { question: "Where was the first controlled nuclear chain reaction achieved?", answer: "University of Chicago, USA", lat: 41.7900, lng: -87.5994, regionRadiusKm: 40, info: "Fermi's team built Chicago Pile‑1 under a stadium in Chicago.", category: "science" },
  { question: "Where is the Arecibo radio telescope site?", answer: "Arecibo region, Puerto Rico", lat: 18.3444, lng: -66.7528, regionRadiusKm: 60, info: "A huge dish was built in a natural sinkhole in Puerto Rico's karst hills.", category: "science" },
  { question: "Where is the Mauna Kea observatory cluster?", answer: "Summit of Mauna Kea, Hawaii, USA", lat: 19.8207, lng: -155.4681, regionRadiusKm: 40, info: "Thirteen large telescopes sit above much of Earth's atmosphere on the volcano's summit.", category: "science" },
  { question: "Where was Marie Curie's radium lab?", answer: "Paris left bank, France", lat: 48.8448, lng: 2.3452, regionRadiusKm: 40, info: "Curie worked at the Radium Institute in Paris.", category: "science" },
  { question: "Where is Los Alamos National Laboratory?", answer: "Northern New Mexico, USA", lat: 35.8800, lng: -106.3031, regionRadiusKm: 60, info: "The Manhattan Project and later nuclear research were based here.", category: "science" },
  { question: "Where is the world's deepest lake by volume?", answer: "Lake Baikal region, Russia", lat: 53.5587, lng: 108.1650, regionRadiusKm: 200, info: "Baikal is both extremely deep and long, holding vast amounts of water.", category: "science" },
  { question: "Where did Charles Darwin find key evidence for evolution?", answer: "Galápagos Islands region, Ecuador", lat: -0.9538, lng: -90.9656, regionRadiusKm: 200, info: "Differences among island species inspired Darwin's ideas on natural selection.", category: "science" },
  { question: "Where is Greenwich and the Prime Meridian?", answer: "Greenwich in London, England", lat: 51.4769, lng: -0.0005, regionRadiusKm: 30, info: "Longitude 0° passes through the Royal Observatory.", category: "science" },
  { question: "Where was the first heart transplant performed?", answer: "Cape Town, South Africa", lat: -33.9248, lng: 18.4041, regionRadiusKm: 60, info: "Christiaan Barnard operated at Groote Schuur Hospital in Cape Town.", category: "science" },
  { question: "Where is the European Southern Observatory's VLT?", answer: "Atacama Desert in northern Chile", lat: -24.6275, lng: -70.4044, regionRadiusKm: 80, info: "The Very Large Telescope complex sits atop Cerro Paranal.", category: "science" },
  { question: "Where was the first IVF baby born?", answer: "Oldham region, England", lat: 53.5440, lng: -2.1170, regionRadiusKm: 40, info: "Louise Brown was born at Oldham General Hospital in 1978.", category: "science" },
  { question: "Where is the National Ignition Facility?", answer: "Livermore, California, USA", lat: 37.6879, lng: -121.7060, regionRadiusKm: 40, info: "The NIF at Lawrence Livermore National Laboratory conducts laser‑driven fusion experiments.", category: "science" },
  { question: "Where is the world's largest single-dish radio telescope FAST?", answer: "Guizhou Province, China", lat: 25.6530, lng: 106.8570, regionRadiusKm: 80, info: "FAST is nestled in a natural karst depression in southwest China.", category: "science" },
  { question: "Where is Fermilab?", answer: "Batavia region near Chicago, USA", lat: 41.8319, lng: -88.2618, regionRadiusKm: 50, info: "Fermilab's accelerators once pushed the Tevatron to record energies.", category: "science" },
  { question: "Where is JAXA's Tsukuba Space Center?", answer: "Tsukuba Science City, Japan", lat: 36.0565, lng: 140.1254, regionRadiusKm: 40, info: "Japan's main space facilities sit in Tsukuba northeast of Tokyo.", category: "science" },
  { question: "Where is ISRO headquartered?", answer: "Bengaluru region, India", lat: 12.9716, lng: 77.5946, regionRadiusKm: 60, info: "India's space agency coordinates missions from Bengaluru in southern India.", category: "science" },
  { question: "Where is NASA's Kennedy Space Center?", answer: "Florida's Space Coast, USA", lat: 28.5729, lng: -80.6490, regionRadiusKm: 80, info: "Launch pads line the barrier islands east of Orlando.", category: "science" },
  { question: "Where is the Keck Observatory?", answer: "Ridge of Mauna Kea, Hawaii, USA", lat: 19.8283, lng: -155.4783, regionRadiusKm: 40, info: "Twin 10m telescopes sit near the summit with other observatories.", category: "science" },
  { question: "Where is the LIGO gravitational wave detector in the US?", answer: "Hanford region, Washington, USA", lat: 46.455, lng: -119.408, regionRadiusKm: 50, info: "One of the twin L‑shaped LIGO detectors is near Hanford in Washington State.", category: "science" },
  { question: "Where is the Royal Observatory Greenwich?", answer: "Southeast London, England", lat: 51.4769, lng: -0.0005, regionRadiusKm: 30, info: "The observatory overlooks the River Thames and Greenwich Park.", category: "science" },
  { question: "Where is the Sahara meteorite research hot spot?", answer: "Northwest Sahara Desert", lat: 24.0, lng: -8.0, regionRadiusKm: 500, info: "Dark meteorites are easier to spot on the pale sands and hamadas of the Sahara.", category: "science" },
  { question: "Where is the Arctic research station Ny-Ålesund?", answer: "Svalbard archipelago, Norway", lat: 78.923, lng: 11.923, regionRadiusKm: 80, info: "Ny‑Ålesund is one of the world's northernmost permanently inhabited settlements.", category: "science" },
  { question: "Where is the European Spaceport?", answer: "Kourou region, French Guiana", lat: 5.239, lng: -52.768, regionRadiusKm: 80, info: "The Guiana Space Centre launches Ariane, Soyuz and Vega rockets near the equator.", category: "science" },
  { question: "Where is the world's longest cave system located?", answer: "Mammoth Cave area, Kentucky, USA", lat: 37.1874, lng: -86.1007, regionRadiusKm: 80, info: "Hundreds of kilometres of tunnels snake under Kentucky's karst landscape.", category: "science" },
  { question: "Where is the Galapagos research station?", answer: "Santa Cruz Island, Ecuador", lat: -0.7436, lng: -90.3044, regionRadiusKm: 60, info: "The Charles Darwin Research Station coordinates conservation efforts in the islands.", category: "science" },
  { question: "Where is the world's most active volcano Kilauea?", answer: "Hawaii's Big Island, USA", lat: 19.4210, lng: -155.2876, regionRadiusKm: 80, info: "Kilauea has erupted frequently for decades along Hawaii's south coast.", category: "science" }
];

export const WHEREIOUS_ENTERTAINMENT = [
  { question: "Where were most scenes of The Lord of the Rings films shot?", answer: "Central New Zealand around Wellington", lat: -41.2865, lng: 174.7762, regionRadiusKm: 250, info: "New Zealand's varied landscapes stood in for Middle‑earth.", category: "entertainment" },
  { question: "Where was Game of Thrones heavily filmed?", answer: "Northern Ireland region, UK", lat: 54.6, lng: -6.7, regionRadiusKm: 200, info: "Many Westeros locations were shot along the coast and countryside of Northern Ireland.", category: "entertainment" },
  { question: "Where were Star Wars' original Tatooine desert scenes filmed?", answer: "Southern Tunisia", lat: 33.0, lng: 9.5, regionRadiusKm: 250, info: "Desert sets and troglodyte houses near Matmata and Tozeur became Tatooine.", category: "entertainment" },
  { question: "Where were many exterior shots for Hogwarts in the Harry Potter films filmed?", answer: "Northern England and Scottish Highlands, UK", lat: 55.0, lng: -3.5, regionRadiusKm: 350, info: "Castles, viaducts and lochs across northern Britain doubled as Hogwarts and its surroundings.", category: "entertainment" },
  { question: "Where is Hollywood, the centre of the American film industry?", answer: "Los Angeles basin, California, USA", lat: 34.0928, lng: -118.3287, regionRadiusKm: 80, info: "Studios and backlots cluster around Hollywood and Burbank in LA.", category: "entertainment" },
  { question: "Where is Bollywood based?", answer: "Mumbai metropolitan region, India", lat: 19.0760, lng: 72.8777, regionRadiusKm: 80, info: "The Hindi‑language film industry is centred in and around Mumbai.", category: "entertainment" },
  { question: "Where is Nollywood, Nigeria's film industry, centred?", answer: "Lagos region, Nigeria", lat: 6.5244, lng: 3.3792, regionRadiusKm: 80, info: "Lagos is the main hub for Nigeria's prolific film production.", category: "entertainment" },
  { question: "Where is Pinewood Studios located?", answer: "Buckinghamshire outside London, England", lat: 51.5481, lng: -0.5340, regionRadiusKm: 40, info: "The studios near Slough have hosted Bond and Star Wars productions.", category: "entertainment" },
  { question: "Where was The Matrix primarily filmed?", answer: "Sydney region, Australia", lat: -33.8688, lng: 151.2093, regionRadiusKm: 80, info: "Although set in a generic city, many scenes used Sydney streets and studios.", category: "entertainment" },
  { question: "Where was Titanic's giant ship set and tank filmed?", answer: "Rosarito Beach area, Baja California, Mexico", lat: 32.329, lng: -117.053, regionRadiusKm: 80, info: "Fox built a huge water tank and partial ship in northern Mexico for the film.", category: "entertainment" },
  { question: "Where was The Sound of Music filmed?", answer: "Salzburg region, Austria", lat: 47.8024, lng: 13.0443, regionRadiusKm: 70, info: "Locations in and around Salzburg doubled as the von Trapp family's Austria.", category: "entertainment" },
  { question: "Where was La La Land mostly shot?", answer: "Los Angeles, California, USA", lat: 34.0522, lng: -118.2437, regionRadiusKm: 60, info: "The musical uses real LA locations from freeways to Griffith Observatory.", category: "entertainment" },
  { question: "Where were many Wakanda landscapes for Black Panther inspired and filmed?", answer: "South Africa and East African‑like savannas", lat: -25.0, lng: 28.0, regionRadiusKm: 400, info: "Production drew heavily on southern African scenery and culture.", category: "entertainment" },
  { question: "Where was Crouching Tiger, Hidden Dragon filmed?", answer: "Chinese mountain and bamboo forest regions", lat: 30.0, lng: 118.0, regionRadiusKm: 400, info: "Scenic locations across Anhui and other provinces provided its lush backdrops.", category: "entertainment" },
  { question: "Where was the Hobbiton village set built for The Lord of the Rings and The Hobbit?", answer: "Waikato region, New Zealand", lat: -37.872, lng: 175.682, regionRadiusKm: 60, info: "A permanent Hobbiton movie set stands near Matamata on a working farm.", category: "entertainment" },
  { question: "Where is Stranger Things mainly shot?", answer: "Atlanta region, Georgia, USA", lat: 33.7490, lng: -84.3880, regionRadiusKm: 120, info: "Many Hawkins, Indiana locations are actually in and around Atlanta.", category: "entertainment" },
  { question: "Where was Breaking Bad filmed?", answer: "Albuquerque region, New Mexico, USA", lat: 35.0844, lng: -106.6504, regionRadiusKm: 80, info: "The desert and cityscapes of Albuquerque define the show's look.", category: "entertainment" },
  { question: "Where was Friends actually filmed?", answer: "Studio lots in Los Angeles, California, USA", lat: 34.1480, lng: -118.3372, regionRadiusKm: 40, info: "Although set in New York, the show was shot on stages in LA.", category: "entertainment" },
  { question: "Where was the US version of The Office shot?", answer: "Los Angeles region, California, USA", lat: 34.201, lng: -118.35, regionRadiusKm: 40, info: "The Scranton paper company was brought to life on LA soundstages and locations.", category: "entertainment" },
  { question: "Where were Frozen's landscapes largely inspired from?", answer: "Western Norway fjords", lat: 61.0, lng: 7.0, regionRadiusKm: 250, info: "Disney artists travelled through Norwegian fjord country for reference.", category: "entertainment" },
  { question: "Where is Disney's main animation studio?", answer: "Burbank, California, USA", lat: 34.1558, lng: -118.3249, regionRadiusKm: 40, info: "Walt Disney Animation Studios is based in the Burbank lot near LA.", category: "entertainment" },
  { question: "Where was Spirited Away animated?", answer: "Tokyo region, Japan", lat: 35.705, lng: 139.561, regionRadiusKm: 40, info: "Studio Ghibli produced the film in its Tokyo‑area studios.", category: "entertainment" },
  { question: "Where were The Lion King's savanna scenes inspired by?", answer: "East African savannas in Kenya and Tanzania", lat: -2.5, lng: 35.0, regionRadiusKm: 350, info: "Artists visited national parks in Kenya and Tanzania for reference.", category: "entertainment" },
  { question: "Where is the Cannes Film Festival held?", answer: "Cannes on the French Riviera", lat: 43.5528, lng: 7.0174, regionRadiusKm: 30, info: "The festival uses the Palais des Festivals beside Cannes' seafront.", category: "entertainment" },
  { question: "Where is the Toronto International Film Festival centred?", answer: "Downtown Toronto, Canada", lat: 43.646, lng: -79.391, regionRadiusKm: 40, info: "TIFF events cluster around King Street West and the Entertainment District.", category: "entertainment" },
  { question: "Where was Mad Max: Fury Road filmed?", answer: "Namib Desert region, Namibia", lat: -24.0, lng: 15.3, regionRadiusKm: 400, info: "The production moved from Australia to Namibia's empty desert landscapes.", category: "entertainment" },
  { question: "Where was much of Planet Earth's desert episode filmed?", answer: "Sahara and other world deserts", lat: 23.5, lng: 13.0, regionRadiusKm: 900, info: "Camera crews visited vast arid regions like the Sahara and Namib deserts.", category: "entertainment" },
  { question: "Where were Avatar's floating mountains inspired by?", answer: "Zhangjiajie region, China", lat: 29.3256, lng: 110.4349, regionRadiusKm: 80, info: "The sandstone pillars of Zhangjiajie National Forest Park inspired Pandora's landscapes.", category: "entertainment" },
  { question: "Where are The Mandalorian's high-tech Volume stages located?", answer: "Los Angeles area, California, USA", lat: 34.201, lng: -118.35, regionRadiusKm: 40, info: "Industrial Light & Magic built LED Volume stages near LA for the series.", category: "entertainment" },
  { question: "Where was Rocky's famous steps run filmed?", answer: "Philadelphia, Pennsylvania, USA", lat: 39.9656, lng: -75.1809, regionRadiusKm: 40, info: "Rocky runs up the steps of the Philadelphia Museum of Art.", category: "entertainment" }
];

export const WHEREIOUS_INVENTIONS = [
  { question: "Where was the World Wide Web invented?", answer: "CERN near Geneva, Switzerland", lat: 46.2322, lng: 6.0554, regionRadiusKm: 80, info: "Tim Berners‑Lee proposed the web at CERN in 1989.", category: "inventions" },
  { question: "Where was the telephone first patented?", answer: "Boston region, Massachusetts, USA", lat: 42.3601, lng: -71.0589, regionRadiusKm: 80, info: "Alexander Graham Bell filed key patents while working in the Boston area.", category: "inventions" },
  { question: "Where did Thomas Edison commercialise the light bulb?", answer: "New Jersey laboratory region, USA", lat: 40.552, lng: -74.278, regionRadiusKm: 60, info: "Edison's Menlo Park and later West Orange labs developed practical incandescent lamps.", category: "inventions" },
  { question: "Where did Johannes Gutenberg develop the movable-type printing press?", answer: "Mainz region, Germany", lat: 50.0, lng: 8.27, regionRadiusKm: 60, info: "Gutenberg's workshop in Mainz produced the famous 42‑line Bible.", category: "inventions" },
  { question: "Where did James Watt improve the steam engine for industry?", answer: "Midlands and Lowlands of Britain", lat: 55.865, lng: -4.257, regionRadiusKm: 350, info: "Watt worked in Glasgow and partnered with Matthew Boulton in Birmingham.", category: "inventions" },
  { question: "Where was the first powered airplane flight made?", answer: "Kitty Hawk region, North Carolina, USA", lat: 36.0140, lng: -75.6710, regionRadiusKm: 60, info: "The Wright brothers flew on the windy dunes near Kitty Hawk in 1903.", category: "inventions" },
  { question: "Where was the first mass-produced car, the Model T, built?", answer: "Detroit region, Michigan, USA", lat: 42.3314, lng: -83.0458, regionRadiusKm: 80, info: "Ford's assembly lines in Detroit revolutionised manufacturing.", category: "inventions" },
  { question: "Where was one of the first programmable electronic computers built?", answer: "Manchester region, England", lat: 53.4808, lng: -2.2426, regionRadiusKm: 60, info: "Manchester's 'Baby' and subsequent machines pioneered stored‑program computing.", category: "inventions" },
  { question: "Where was the first modern smallpox vaccine demonstrated?", answer: "Berkeley region, Gloucestershire, England", lat: 51.6978, lng: -2.4598, regionRadiusKm: 40, info: "Edward Jenner tested cowpox inoculation in rural England.", category: "inventions" },
  { question: "Where was the first effective polio vaccine rolled out?", answer: "Pittsburgh region, Pennsylvania, USA", lat: 40.4406, lng: -79.9959, regionRadiusKm: 60, info: "Jonas Salk developed his vaccine at the University of Pittsburgh.", category: "inventions" },
  { question: "Where was the first civilian nuclear power plant built?", answer: "Obninsk region, Russia", lat: 55.09, lng: 36.61, regionRadiusKm: 60, info: "The Obninsk plant near Moscow began operating in 1954.", category: "inventions" },
  { question: "Where was the first practical photographic process developed?", answer: "Paris region, France", lat: 48.8566, lng: 2.3522, regionRadiusKm: 60, info: "Daguerre and Niépce worked in and around Paris on early photography.", category: "inventions" },
  { question: "Where were early motion picture cameras and projectors developed?", answer: "New Jersey and New York region, USA", lat: 40.7357, lng: -74.1724, regionRadiusKm: 120, info: "Edison's labs and other inventors around the US east coast built early film cameras.", category: "inventions" },
  { question: "Where were the modern Olympic Games revived in 1896?", answer: "Athens region, Greece", lat: 37.9838, lng: 23.7275, regionRadiusKm: 40, info: "The first modern Olympics were held in Athens' Panathenaic Stadium.", category: "inventions" },
  { question: "Where was the first general-purpose credit card system pioneered?", answer: "New York region, USA", lat: 40.7128, lng: -74.0060, regionRadiusKm: 80, info: "Diners Club and later cards emerged from US financial centres.", category: "inventions" },
  { question: "Where was the first ATM installed?", answer: "Enfield area, London, England", lat: 51.6520, lng: -0.0807, regionRadiusKm: 40, info: "Barclays deployed the first cash machine at a branch in Enfield in 1967.", category: "inventions" },
  { question: "Where was the compact disc (CD) developed?", answer: "Tokyo region, Japan", lat: 35.6762, lng: 139.6503, regionRadiusKm: 80, info: "Sony and Philips engineers refined the CD in labs in Japan and Europe.", category: "inventions" },
  { question: "Where was one of the first smartphones, the IBM Simon, developed?", answer: "US east coast technology corridor", lat: 41.76, lng: -72.67, regionRadiusKm: 300, info: "IBM's early smartphone work was done in American labs and offices.", category: "inventions" },
  { question: "Where was the GPS satellite navigation system operated from?", answer: "Colorado and US military facilities", lat: 39.7420, lng: -104.99, regionRadiusKm: 400, info: "The US Air Force manages GPS from control stations in Colorado and elsewhere.", category: "inventions" },
  { question: "Where was the first commercially successful video game Pong created?", answer: "Silicon Valley region, California, USA", lat: 37.3688, lng: -121.9270, regionRadiusKm: 80, info: "Atari developed Pong in Sunnyvale, California.", category: "inventions" },
  { question: "Where was insulin first isolated and used successfully in patients?", answer: "Toronto region, Canada", lat: 43.6629, lng: -79.3957, regionRadiusKm: 60, info: "Banting and Best worked at the University of Toronto in the early 1920s.", category: "inventions" },
  { question: "Where was the first email sent over ARPANET?", answer: "Boston area, Massachusetts, USA", lat: 42.378, lng: -71.116, regionRadiusKm: 80, info: "Ray Tomlinson sent the first networked email between neighbouring machines in the early 1970s.", category: "inventions" },
  { question: "Where was modern 3D printing (stereolithography) invented?", answer: "California region, USA", lat: 33.7455, lng: -117.866, regionRadiusKm: 120, info: "Chuck Hull developed stereolithography and founded 3D Systems in California.", category: "inventions" },
  { question: "Where was the integrated circuit (microchip) created?", answer: "Texas region, USA", lat: 32.7767, lng: -96.7970, regionRadiusKm: 200, info: "Jack Kilby built the first integrated circuit at Texas Instruments in Dallas.", category: "inventions" },
  { question: "Where was one of the first modern submarines developed?", answer: "US east coast shipyards", lat: 41.37, lng: -72.09, regionRadiusKm: 250, info: "Early submarine designs were tested in American and European naval yards.", category: "inventions" },
  { question: "Where were some of the first mechanical public clock towers built?", answer: "Central and western Europe", lat: 48.0, lng: 9.0, regionRadiusKm: 600, info: "Medieval towns across Europe installed mechanical clocks in church towers.", category: "inventions" },
  { question: "Where was an early successful colour photography process used?", answer: "France", lat: 48.8566, lng: 2.3522, regionRadiusKm: 400, info: "The Lumière brothers in France developed the Autochrome process.", category: "inventions" },
  { question: "Where was the modern bicycle's forerunner developed?", answer: "Mannheim region, Germany", lat: 49.4875, lng: 8.4660, regionRadiusKm: 60, info: "Karl Drais invented an early two‑wheeled 'running machine' here.", category: "inventions" },
  { question: "Where were instant noodles first invented?", answer: "Osaka region, Japan", lat: 34.6937, lng: 135.5023, regionRadiusKm: 80, info: "Momofuku Ando created Chikin Ramen near Osaka in 1958.", category: "inventions" },
  { question: "Where was the first wave of personal computers like the Apple I and II created?", answer: "Silicon Valley region, California, USA", lat: 37.3318, lng: -122.0308, regionRadiusKm: 80, info: "Apple and other early PC companies grew up in the San Francisco Bay Area.", category: "inventions" }
];

export const ALL_WHEREIOUS_EVENTS = [
  ...WHEREIOUS_LANDMARKS,
  ...WHEREIOUS_NATURE_REGIONS,
  ...WHEREIOUS_HISTORY_REGIONS,
  ...WHEREIOUS_GEOGRAPHY,
  ...WHEREIOUS_PEOPLE,
  ...WHEREIOUS_RECORDS,
  ...WHEREIOUS_SCIENCE_REGIONS,
  ...WHEREIOUS_ENTERTAINMENT,
  ...WHEREIOUS_INVENTIONS
];

